### ISSUE TITLE
Cannot generate figure

### ISSUE THREAD

**Issue by LanceKnight** [ACCLAB/DABEST-python#100]
Hello, I cannot generate figure, neither following the demo on this repository nor the official tutorial.

test.py below is the codes from the official tutorial, and demo.py is the codes from this repo

```
(basic3) lanceknight@Lance-Ubuntu:~/tests/dabest$ python test.py 
(basic3) lanceknight@Lance-Ubuntu:~/tests/dabest$ vim demo.py
(basic3) lanceknight@Lance-Ubuntu:~/tests/dabest$ python demo.py 
(basic3) lanceknight@Lance-Ubuntu:~/tests/dabest$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
(basic3) lanceknight@Lance-Ubuntu:~/tests/dabest$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
cycler (0.10.0)
dabest (0.3.0)
kiwisolver (1.2.0)
lqrt (0.3.3)
matplotlib (3.2.1)
numpy (1.18.3)
pandas (0.25.3)
pip (9.0.1)
pkg-resources (0.0.0)
pyparsing (2.4.7)
python-dateutil (2.8.1)
pytz (2019.3)
scipy (1.4.1)
seaborn (0.10.0)
setuptools (39.0.1)
six (1.14.0)
(basic3) lanceknight@Lance-Ubuntu:~/tests/dabest$ 
```
basically after "python demo.py", there is no response at all. Matplotlib works fine on my machine. Other info are also shown above

**Comment by josesho** [comment]
Hi @LanceKnight ,

The official tutorial does not save any generated images to disk. Have you tried running the example code in the [Readme](https://github.com/ACCLAB/DABEST-python#usage) in a Jupyter notebook?

**Comment by josesho** [comment]
Closing for now. If you have any follow ups, just open and add a comment. Thanks!

**Comment by LanceKnight** [comment]
Hi, sorry I didn’t see your reply. It can be closed. Thanks!
