### ISSUE TITLE
 module 'dabest' has no attribute '__version__'

### ISSUE THREAD

**Issue by pawansingh786125** [ACCLAB/DABEST-python#102]
After installation this error is shown on console.
import dabest
print("We're using DABEST v{}".format(dabest .__version__))

console:

  File "C:/Users/doctor/.spyder-py3/learn dabest.py", line 14, in <module>
    print("We're using DABEST v{}"(dabest .__version__))

AttributeError: module 'dabest' has no attribute '__version__

**Comment by josesho** [comment]
Hi,

Are you running 

```python
print("We're using DABEST v{}".format(dabest.__version__))
```
(which is correct)

or 

```python
print("We're using DABEST v{}".format(dabest.version))
```
(which is wrong)?

**Comment by pawansingh786125** [comment]
Thanks for your mail.
The problem has been solved. The issue was regarding the settings update
for Spyder. The code was taking some previously written code with dabest.
After restarting  multiple times the system and deleting the older programs
written with dabest, it started working.
