### ISSUE TITLE
color_col formatting

### ISSUE THREAD

**Issue by MPMorton** [ACCLAB/DABEST-python#103]
Could you provide me some more info on how color_col is supposed to work and how the data is supposed to be formatted? I think I'm doing things exactly like the tutorial. I attached the code and data I can't get to work. Basically if I use `mean_diff.plot()` it works without color, but `mean_diff.plot(color_col="Type")` does not, and gives the following error: 

```
Traceback (most recent call last):

  File "/Users/mm/Documents/F_test.py", line 10, in <module>
    F_dabest.mean_diff.plot(color_col="Type");

  File "/Users/mm/opt/anaconda3/lib/python3.7/site-packages/dabest/_classes.py", line 1693, in plot
    out = EffectSizeDataFramePlotter(self, **all_kwargs)

  File "/Users/mm/opt/anaconda3/lib/python3.7/site-packages/dabest/plotter.py", line 377, in EffectSizeDataFramePlotter
    slopegraph_kwargs['color']  = plot_palette_raw[color_key]

KeyError: nan

```

Thanks for any help! 

[F.zip](https://github.com/ACCLAB/DABEST-python/files/5057025/F.zip)

**Comment by josesho** [comment]
I can replicate your error. I'm not sure what exactly is causing it, let me get back!

**Comment by Jacobluke-** [comment]
This bug is resolved.
