### ISSUE TITLE
pandas version conflicts

### ISSUE THREAD

**Issue by mjoppich** [ACCLAB/DABEST-python#104]
Hi,

is pandas 0.x really required, or does it also work with higher versions of pandas?

If so, would it be possible to take out the version requirement from the setup.py install_requires ?

Thanks!

Markus

**Comment by josesho** [comment]
Yes, thanks for sounding this out. I'll push and release v0.3.1 soon, which updates the dependencies.

**Comment by josesho** [comment]
Done! Let me know if there's any problems.
