### ISSUE TITLE
Estimation plot only

### ISSUE THREAD

**Issue by llobetv** [ACCLAB/DABEST-python#118]
Hi,

I appreciate the estimation plot so I would like to use them, but since I have to make my own dedicated bootstrap (hierarchical bootstrap) I cannot used dabest functions. 

Is their a way to give bootstrap values, CI calculated and sample point to generate estimation plot?

Best regards,
Victor

**Comment by josesho** [comment]
Hi @llobetv ,

You can take a look at [`plot_tools.py`](https://github.com/ACCLAB/DABEST-python/blob/master/dabest/plot_tools.py) as a starting point for utility functions.

Thanks,
Joses
