### ISSUE TITLE
DABEST calculation of median difference CIs often fails 

### ISSUE THREAD

**Issue by seamusholden** [ACCLAB/DABEST-python#129]
We are frequently running into a problem that, for sensible looking datasets which are quantized but have large sample size, calculation of the median difference confidence interval fails in at least 50% of cases.

**To summarise the below tests:**_: I suspect there is a bug in either the acceleration or the bias for the BCa calculation in compute_interval_limits in confint_2group_diff.py which is causing undefined confidence intervals for the median difference calculation. But I dont understant the BCa calculation well enough to diagnose the issue further. Any advice/ help appreciated_

I've attached some test data showing the issue:
[Data.csv](https://github.com/ACCLAB/DABEST-python/files/8426077/Data.csv)

The data are quantized and somewhat skewed so we mainly look at medians to summarize the data. There are quite a few data points (hundreds per sample) and a decent spread so we should not expect run into known issues with bootstrap median calculations issues where we mainly obtain the same median value for each bootstrap.

If we run the median difference analysis, the "B-Ref" comparison fails to calculate confidence intervals, even though we can see that the estimated PDF is clearly defined:
```
import numpy
import pandas
import dabest
import matplotlib.pyplot as plt
df = pandas.read_csv('Data.csv')
life_dabest = dabest.load(data=df, x = "X", 
                          y = "Y",
                          idx=('Ref','A',
                                "B"))
plt.figure()
fig = life_dabest.median_diff.plot()
```
Outputs:

> C:\Users\nsh167\Anaconda3\lib\site-packages\dabest\_classes.py:792: UserWarning: The lower limit of the BCa interval cannot be computed. It is set to the effect size itself. All bootstrap values were likely all the same.
>   stacklevel=0)
> C:\Users\nsh167\Anaconda3\lib\site-packages\dabest\_classes.py:797: UserWarning: The upper limit of the BCa interval cannot be computed. It is set to the effect size itself. All bootstrap values were likely all the same.
>   stacklevel=0)
![image](https://user-images.githubusercontent.com/6583104/161956448-d57ea690-d0bd-4d06-a048-1559a8cab162.png)

From looking at the code it looks like a failure in calculating either the acceleration or the bias for the BCa calculation in compute_interval_limits in confint_2group_diff.py.

However if we add a negligible amount of noise to the data - just enough so that strictly the data are no longer quantized, but not enough to affect the spread of the data in any meaningful way, the CI calculation works fine. However, I am a not completely comfortable about using this quite ad hoc approach as a workaround!
```
df2=df
n = len(df2['Y'] )
noise = numpy.random.normal(0, 0.0001, n)
df2['Y']=df2['Y']+noise

life_dabest2 = dabest.load(data=df2, x = "X", 
                          y = "Y",
                          idx=('Ref','A',
                                "B"))
plt.figure()
fig2 = life_dabest2.median_diff.plot()
```
![image](https://user-images.githubusercontent.com/6583104/161956712-223841ec-aa9a-44c6-8a44-c1f585b48e03.png)

As a further sanity check I tested whether I could reproduce the issue in MATLAB. Basically to get an idea whether it was more likely to be a statistics or code issue.  The standard DABEST-MATLAB package does not do median difference plots, so a while ago I hacked together a simple derivative package:
https://github.com/HoldenLab/violinplusDABEST-Matlab

This package uses the MATLAB bootci function, which also uses the BCa method seems to be able to calculate 
Interestingly, the MATLAB function can calculate the CIs just fine, and looks identical to the 2nd python plot
```
tmp=importdata('Data.csv');

data = tmp.data;
cats = tmp.textdata(2:end,1);
grouporder ={'Ref','A','B'};

violinplusdabest(data,cats,{'Ref','A','B'})
```
![image](https://user-images.githubusercontent.com/6583104/161961795-e8a6d4f5-91c5-47ff-97fd-422d0c7a91a2.png)

**Comment by josesho** [comment]
Hi @seamusholden , 

this is indeed curious, let me take a closer look at get back to you....

**Comment by seamusholden** [comment]
Thanks!

**Comment by Jacobluke-** [comment]
Hi @seamusholden , 

For your zero-width interval problem, this lies not in the calculation itself, but the data. To calculate the BCa interval, one should use jackknife method to calculate the corresponding acceleration value, and the jackknife method removes one element in the sample and calculate the desired statistic. For effect size you choose being the median, along with the data points in your sample crowded in the median, the jackknife method always generate the same value and the denominator in calculating the acceleration value will be zero, which causes the the problem of zero-width. 

We benchmark this dataset with this dataset and it generates a result similar to DABEST-Matlab. The reason is that in these two we directly apply BCa interval without using jackknife method, so it looks like "no problem". We will fix the bug in dabestr.

Hope it clarifies your problem.

**Comment by seamusholden** [comment]
Thanks for looking into that so thoroughly. Are you sure that the current MATLAB/ R bootstrap CI implementations are faulty? It seems like the jacknife accelaration calculation is failing for the quantized data, rather than producing reasonable results.

As usual the MATLAB implementation is a bit unclear but refers to issues with "lumpy" data suggesting that indeed workarounds for quantized data are resonable - and surely the fact that both the ad hoc add a small amount of noise approach and the matlab bootci function give the same CI distribution supports this?

From MATLAB help file regards how the acceleration parameter is calculated:

> Bias corrected and accelerated percentile method [[3]](https://uk.mathworks.com/help/stats/bootci.html#brx09qf-182_sep_shared-DiCiccio1996), [[4]](https://uk.mathworks.com/help/stats/bootci.html#brx09qf-182_sep_shared-Efron1993). This method involves a z0 factor computed using the proportion of bootstrap values that are less than the original sample value. To produce reasonable results when the sample is lumpy, the software computes z0 by including half of the bootstrap values that are the same as the original sample value.

**Comment by Jacobluke-** [comment]
Hi @seamusholden ，

Thanks for pointing out the problem. The MATLAB does provide a reasonable workaround for the quantized, or lumpy, type of data. If the calculation of acceleration follows the original jackknife method, it cannot produce a reasonable results. But for the dabestr, there is a parameter lacking to ensure the program using jackknife method to generate the acceleration value. See [empinf function documentation](https://www.rdocumentation.org/packages/boot/versions/1.3-28.1/topics/empinf)

<img width="1047" alt="CleanShot 2023-01-11 at 19 23 47@2x" src="https://user-images.githubusercontent.com/10691706/215333995-c6f1d2db-7d25-4304-b487-e3b688f95f15.png">

As we mentioned earlier, jackknife method is failing for quantized (lumpy) data, and it's even worse when dealing with quantile statistics. For bootstrapping, it's recommended to avoid using quantile statistics like median.

 **Further action**

- We will give users the option of choosing which kind of confidence interval to be used in the plot
- We will add warnings about choosing quantile statistics in bootstrapping
- Fix the parameter problem of dabestr.

Cheers,
@Jacobluke-
