### ISSUE TITLE
Error in bca.ci(boot.out, conf, index[1L], L = L, t = t.o, t0 = t0.o,  :    estimated adjustment 'a' is NA

### ISSUE THREAD

**Issue by salihtuna** [ACCLAB/DABEST-python#130]
I am running the dabest() function in R with the following options but getting the following error message. My understanding is that if i increase the bootstrap replications it might help with the problem? However, I could not find this option the dabest() function (i.e. to change the number of bootstrap replications). Or do you think the problem is something else?

`  
unpaired_mean_diff <- dabest(df, X, Y,
                             idx = c("A", "B", "C"),
                             paired = FALSE) %>% 
  mean_diff()
`
```
Error in bca.ci(boot.out, conf, index[1L], L = L, t = t.o, t0 = t0.o,  : 
  estimated adjustment 'a' is NA
```

**Comment by josesho** [comment]
Could I trouble you to move this issue over to https://github.com/ACCLAB/dabestr/issues? Thanks!

Also please provide a copy-pastable example, much appreciated!
