### ISSUE TITLE
Error in changing the the linewidth of the lines used to join each pair of observations

### ISSUE THREAD

**Issue by XYZfar** [ACCLAB/DABEST-python#142]
I was trying to change the the linewidth of the lines used to join each pair of observations by using the code
`slopegraph_kwargs= {'linewidth':2,'alpha':1}` according to the API.
However I had this error

![image](https://user-images.githubusercontent.com/19358205/227413838-21d3fa9d-7bee-4453-8c75-d7024a7214b2.png)

When I change the code to
`slopegraph_kwargs= {'lw':2,'alpha':1}`
Then it works.

**Comment by Jacobluke-** [comment]
Hi! 

Thanks for the feedback on this bug. The appropriate parameter for this should be 'lw'. We made a mistake on the tutorial. 

Regards,
@Jacobluke-
