### ISSUE TITLE
Options for plot appearance

### ISSUE THREAD

**Issue by dickinson-lab** [ACCLAB/DABEST-python#156]
First of all, thank you for your outstanding toolkit, which has greatly improved our data analysis workflows. 

I have used the MATLAB version of DABEST a lot, but it hasn't been updated recently and there are a lot of good reasons to use Python instead.  So, I am trying to switch over.  However, I prefer the appearance of the plots in the MATLAB version, especially 1) the way that the mean/median and 95% CI are shown as error bars on top of the data (rather than the bar with a gap to the side) and 2) The way the 95% CI of the difference is shown as an error bar rather than the half-violin plot.  

Is there an option to have the Python version plot the data with a similar appearance to the MATLAB version, or could this feature be added?

**Comment by dickinson-lab** [comment]
You can disregard the comment above - from the API reference given, I think I see now how I can get the results in numeric format so I can plot them however I want. 

As an aside, there appear to be two different versions of the documentation / tutorial on your website: 
https://acclab.github.io/DABEST-python/01-getting_started.html
https://acclab.github.io/DABEST-python-docs/

These contain slightly different information (or maybe the same information but organized differently); this caused me some confusion.

**Comment by Jacobluke-** [comment]
Hi @dickinson-lab , we remove the old documentations and add a redirect link to the newer version.

Thank you for pointing it out!
