### ISSUE TITLE
scaling issues 

### ISSUE THREAD

**Issue by mmyros** [ACCLAB/DABEST-python#16]
Hello,

Thanks for making this package available, it seems very useful
![screenshot from 2018-07-31 12-38-50](https://user-images.githubusercontent.com/3022307/43473774-0e30f6a0-94bf-11e8-961c-6898ad10fd8a.png)
! I am experiencing scaling issues as seen in the attached screenshot. This happens on Mac and CentOS, conda with python 3.6. I am able to save semi-sane pdfs after downscaling the font and stretching the figure a lot, but it's not great. Do you have any insight?

On a related note, do you have any suggestions for integrating these figures in subplots?

Thank you,
Max

**Comment by josesho** [comment]
Hi @mmyros , thanks! Glad you are finding DABEST useful. 

I am aware of scaling issues that you raise, and these should be addressed in v0.1.4. I hope to release a new version by the end of the week, stay tuned!

Re: plotting onto subplots/individual axes, this has been on the backburner. I will have to make more extensive use of the `GridSpec` functionalities in matplotlib. Feel free to submit a PR if you have a quick fix. Plotting onto subplots will have to wait till after v0.1.4.

**Comment by josesho** [comment]
This should be resolved with v0.1.4.
