### ISSUE TITLE
Support newer versions of matplotlib (>=3.8)

### ISSUE THREAD

**Issue by siemdejong** [ACCLAB/DABEST-python#183]
**Is your feature request related to a problem? Please describe.**
I'm using `matplotlibrc` files to distribute styles with packages. This is a feature of `matplotlib>=3.8` if I'm not mistaken. `dabest==2023.03.29` supports `matplotlib~=3.6.3`. Simply installing a newer matplotlib version  (`matplotlib==3.9.1.post1`) and following https://acclab.github.io/DABEST-python/tutorials/06-plot_aesthetics.html throws
```python
AttributeError: module 'matplotlib.axes' has no attribute '_subplots'
```
The `_subplots` attribute has been deprecated in newer matplotlib versions.

**Describe the solution you'd like**
Support newer versions of matplotlib such that I can use style files in conjunction with dabest.

**Describe alternatives you've considered**
- Not using dabest
- accept that dabest sometimes throws errors and some functionality is impossible to use with custom style files.

**Comment by Jacobluke-** [comment]
Hi @siemdejong, thanks for providing solutions for this issue. All the changes has been merged to branch [vnbdev](https://github.com/ACCLAB/DABEST-python/tree/vnbdev).
