### ISSUE TITLE
need to run in  multithread  mode 

### ISSUE THREAD

**Issue by narendrameena** [ACCLAB/DABEST-python#19]
How can I use dabest.plot() in multithread mode? I got a really big matrix.

**Comment by josesho** [comment]
Currently, `dabest` does not feature multi-threading. How big is your 'big' matrix? A single two-group estimation plot of N = 1000, 1000 should take no longer than a few seconds on a typical machine.

You can use cloud services (eg. Google's [Colab](https://colab.research.google.com)) to access higher-capacity computing resources; you just have to install `dabest` first.

Thanks for using this package! Hope this helped.
