### ISSUE TITLE
UnboundLocalError: local variable 'rightmin' referenced before assignment

### ISSUE THREAD

**Issue by sspera** [ACCLAB/DABEST-python#33]
line 533, in EffectSizeDataFramePlotter
    contrast_axes.set_ylim(rightmin, rightmax)
UnboundLocalError: local variable 'rightmin' referenced before assignment

**Comment by josesho** [comment]
Hi @sspera 

Could you please provide a [minimally reproducible example](https://stackoverflow.com/help/mcve)?

I suspect this is the same bug as [this](https://github.com/ACCLAB/DABEST-python/pull/30).

You can try forking this repo, and checking out branch `v0.2.2`, and locally installing it.

Thanks,
Joses

**Comment by josesho** [comment]
Closing as we lack a minimally reproducible example, or further follow-up

**Comment by sspera** [comment]
Hi! Sorry, yes that totally worked, when I installed v0.2.2.

Thank you, sorry for the delay.
