### ISSUE TITLE
plotting error: 95% range overlaps with data

### ISSUE THREAD

**Issue by drbenvincent** [ACCLAB/DABEST-python#35]
Hi. 
I'm loving this code so far. When there is quite a lot of data, there is a slight formatting error where the 95% range marker overlaps with the data. See pic.
![Screenshot 2019-04-16 at 16 43 52](https://user-images.githubusercontent.com/6765047/56224064-dea81980-6066-11e9-86f1-39d4e15011bd.png)
This is also the case when I tried manually specifying a wider aspect ratio using the `fig_size` parameter.
![Screenshot 2019-04-16 at 16 42 30](https://user-images.githubusercontent.com/6765047/56224341-6130d900-6067-11e9-99f1-e57ef918c8de.png)

**Comment by josesho** [comment]
Hi @drbenvincent ,

Unfortunately, the closest fix right now is to tweak both `raw_marker_size` and `fig_size`:

```python
my_data = dabest.load(data=my_df, idx=("Control 1", "Test 1", "Test 3"))

my_data.mean_diff.plot(raw_marker_size=3, fig_size=(7,5));
```

I will probably include a keyword argument in v0.2.3. Or, if you feel up to it, you can remove the hardcoded x-offset in this [line](https://github.com/ACCLAB/DABEST-python/blob/cf3562307338d81210f176033a67e6a76eb70491/dabest/plotter.py#L370), add the appropriate keyword argument in this line, and submit a PR!

**Comment by drbenvincent** [comment]
> the best fix right now is a bit of a hack: tweak both `raw_marker_size` and `fig_size` until the group ranges don't overlap with the rawdata

Thanks, I'll try this for the moment.
