### ISSUE TITLE
Typo in docstring of plot()

### ISSUE THREAD

**Issue by DizietAsahi** [ACCLAB/DABEST-python#39]
https://github.com/ACCLAB/DABEST-python/blob/7fb35f3a0968cb1010e8530144c9fb205f241901/dabest/_classes.py#L1182

The Figure.axes property of the Figure class is a list, and not a function.
https://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.axes

You would therefore access the two axes using:
`FigName.axes[0]` and `FigName.axes[1]`

**Comment by josesho** [comment]
Thanks for this, I will fix this in the upcoming patch release!
