### ISSUE TITLE
Statistical Question

### ISSUE THREAD

**Issue by MCaviezel** [ACCLAB/DABEST-python#47]
Hi,
Thanks for this wonderful tool you provided!

I was wondering if it is statistically possible to include nuisance parameters in the group comparison?
For example, if I want to compare a biomarker (DV) of two groups (IV1) and control for gender (IV2) and age (IV3).
In a multiple regression setting, I would include these variables in the model or use them as random effects. (Biomarker ~ Group + Gender + Age, respectively  Biomarker ~ Group + (1 | Gender) + (1 | Age))
Is this also possible in bootstrapping?

Thank you and best regards,

Marco

**Comment by josesho** [comment]
From what I can gather, you can do a bootstrap multiple regression, but this is currently out of the scope of DABEST.

If you're interested in performing an ANOVA-style 2x2 analysis, you can use DABEST to create the relevant plots; Rob Calin-Jagerman did a quick demo on [Twitter](https://mobile.twitter.com/thenewstats/status/1141933404939870210).

Hope this helps!
