### ISSUE TITLE
Adjusting font size on legends

### ISSUE THREAD

**Issue by mpiacentino** [ACCLAB/DABEST-python#49]
I'm loving this plotting and analysis pipeline, and am trying to incorporate it into my own work. I'm working on building a script in Python to streamline and make plots that fit my general presentation style for presentations and publications. Currently, as I resize the plot the axis text becomes too large and begins overlapping (example attached). I've included the code I'm using to generate this, and any tips on where/how to revise this to change axis text would be greatly appreciated! I'd like to resize the text, but could also foresee wanting to change the orientation of the text and removing the "n=". 

![nSMase2MO](https://user-images.githubusercontent.com/40148007/61010382-d9d3c880-a32a-11e9-89a7-14ad34fa9b9f.png)

`
# Load data into DABEST as paired dataset
data = dabest.load(dataset, idx=(cntl_dataset, expt_dataset), id_col='Image', paired=True)
# Plot results
fig1 = data.mean_diff.plot(
                fig_size=(3.5,3)                              
                ,dpi=150
                ,reflines_kwargs= {'linestyle':'dashed'      
                               ,'linewidth':.8
                               ,'color' : 'black'}
                ,swarm_label=(yaxis_label)
                ,show_pairs=False                            
                ,swarm_desat=1
                ,group_summaries='mean_sd'                  
                ,group_summaries_offset=0.15
                ,swarmplot_kwargs={'size':5}                 
                ,group_summary_kwargs={'lw':3, 'alpha':0.8}   
                ,float_contrast=True                
                ,contrast_label='paired mean difference'
                ,es_marker_size=5 
                ,halfviolin_desat=1
                ,halfviolin_alpha=0.8
                ,violinplot_kwargs={'widths':0.5}
                             )`

**Comment by josesho** [comment]
Hi @mpiacentino,

Thanks for this. You might want to try updating `seaborn` to `v0.9.x`, and `matplotlib` to `>=3.0`. Also ensure that you have `v0.2.5` of `dabest`? Your swarmplots are squished (dots obscuring each other), which suggests to me either `matplotlib` or `dabest` is not up to date.

Here's what I see when I run your code snippet.

```python
import matplotlib as mpl
import pandas as pd
import seaborn as sns
import dabest

print("matplotlib v{}".format(mpl.__version__))
print("seaborn v{}".format(sns.__version__))
print("dabest v{}".format(dabest.__version__))
```
You should ideally see:
```shell
matplotlib v3.0.3
seaborn v0.9.0
dabest v0.2.4
```

```python
import numpy as np
from scipy.stats import norm

np.random.seed(55555) # Fix the seed so the results are replicable.
Ns = 27 # The number of samples taken from each population

# Create samples
c = norm.rvs(loc=3, scale=0.4, size=Ns)
t = norm.rvs(loc=3.5, scale=0.75, size=Ns)
id_ = range(1, Ns+1)

df = pd.DataFrame({'Control MO' : c, 
                   'SMase2 MO' : t,
                   'id': id_
                  })

# Run dabest analysis
df_analysis = dabest.load(df, idx=('Control MO', 'SMase2 MO'), 
                          id_col='id',
                          paired=True)

# Create Gardner-Altman plot
fig = df_analysis.mean_diff.plot(fig_size=(3.5,3),
                           dpi=150,
                           reflines_kwargs= {'linestyle':'dashed',
                                             'linewidth':0.8,
                                             'color' : 'black'},
                           swarm_label=('Norm Migration Area'),
                           show_pairs=False,
                           swarm_desat=1,
                           group_summaries='mean_sd',
#                            group_summaries_offset=0.15, ## Deprecated keyword.
                           swarmplot_kwargs={'size':5},
                           group_summary_kwargs={'lw':3, 'alpha':0.8},
                           float_contrast=True,
                           contrast_label='paired mean difference',
                           es_marker_size=5,
                           halfviolin_desat=1,
                           halfviolin_alpha=0.8,
                           violinplot_kwargs={'widths':0.5}
                          );

# Rotate ticks 45 degs. 
# See https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_xticklabels.html
for ax in fig.axes:
    ax.set_xticklabels(ax.get_xticklabels(), 
                       rotation=45, horizontalalignment='center')
```
![image](https://user-images.githubusercontent.com/12838917/61026830-1402a000-a3e7-11e9-9f81-dc48ebd9c9aa.png)


I'd also suggest experimenting with `font_scale` in 
```python
sns.set(font_scale=0.9, , style='ticks')
```
to tweak the font size. This however affects all text in the image, not just the x-axis tick labels.

Hope this helps!

**Comment by josesho** [comment]
Closing as the issue has been addressed. Thanks!
