### ISSUE TITLE
axis labels for y axes

### ISSUE THREAD

**Issue by astraw** [ACCLAB/DABEST-python#51]
First off, many thanks for DABEST and everyone's work on estimation statistics.

I was looking at the initial example in `README.md` and see that there is no label on the y axis of the swarmplot. Checking the docstring of `iris_dabest.mean_diff.plot`, I found the kwarg `swarm_label` which allows me to set this. Indeed, using this works. However, the description of the kwarg suggests that it axis will be automatically labeled: 

    If `swarm_label` is not specified, it defaults to
    "value", unless a column name was passed to `y`. If
    `contrast_label` is not specified, it defaults to the effect size
    being plotted.

However, the behavior I see (also shown in the `README.md` plot) is neither "value" nor the column name ("petal_width" in this case), but empty. So, I think there is either a bug in the docstring or the implementation.

Furthermore, I think all plots should have the y axis of the swarmplots labeled by default. I see in [the tutorial](https://acclab.github.io/DABEST-python-docs/tutorial.html), for example, that this is not the case.

**Comment by josesho** [comment]
Thanks for spotting this discrepancy between the docstring, the tutorial, and the actual output! This will be fixed in the forthcoming release.
