### ISSUE TITLE
compare all condition-condition pairs?

### ISSUE THREAD

**Issue by qihongl** [ACCLAB/DABEST-python#55]
If I understand correctly, the package only supports comparing all conditions to one reference condition. 

I thought it would be really neat if dabest can plot more than one reference conditions. For example, I think it would be useful to do all pair-wise comparison (compare condition i vs. condition j for all i, j s.t.  i != j). For example, one possible layout is to use the 0-th row to plot the raw data, and plot a grid of mean difference distributions underneath, where the i-th row uses the i-th condition as the reference condition. 

Thanks!

**Comment by adamcc** [comment]
HI Qihong, 

Thanks for the suggestion, it's a neat idea to show a grid of effect sizes.

For a variety of reasons, we won't be able to develop this in the near future. You are welcome to code this yourself and submit a pull request.

Best, 
Adam

**Comment by josesho** [comment]
Closing this issue for now; if you want to submit a PR, feel free to reference this!
