### ISSUE TITLE
variance +/- 5.

### ISSUE THREAD

**Issue by naarkhoo** [ACCLAB/DABEST-python#56]
For some reason in all examples you have seems the variance is +/-5 ! I wonder if that's because of the model, or rather the sub-optimial selection of the example data?

**Comment by josesho** [comment]
Hi,

Not sure what exactly you mean by "variance ± 5". Could you provide a [concrete copy-pastable example](https://github.com/ACCLAB/DABEST-python/blob/master/CONTRIBUTING.md#did-you-find-a-bug) of what you are referring to?
