### ISSUE TITLE
Hypothesis testing interpretation?

### ISSUE THREAD

**Issue by lrq3000** [ACCLAB/DABEST-python#59]
I'm not entirely sure how to properly interpret the graphs. Let's take the figure 1 from the paper:

![dabest-interpretation](https://user-images.githubusercontent.com/1118942/63991144-dff25400-cae6-11e9-9d6e-d2e6f02bbc31.png)

From what I understand, Figure 1d represent p(data|H0), and here it seems to be just at the 95% threshold (ie, p<0.05, although there is no confidence interval plotted here). Figure 1e, the essence of this toolbox, looks to me to represent p(H0|data), or more precisely here p(C|T), which here seems just at the 95% threshold again.

Is this interpretation correct? If so, is it possible with DABEST to plot H0 distribution like in Figure 1d?

Indeed, I agree that p(H0|data) is more informative than p(data|H0), but still most of NHST is relying on the latter, and it would bring the best of both worlds to be able to plot both inferences. What I would imagine would be something like this:

![dabest-null-distrib](https://user-images.githubusercontent.com/1118942/63991430-18466200-cae8-11e9-80da-5410c0f74322.png)

What do you think, would this be pertinent?

**Comment by lrq3000** [comment]
PS: this question and proposition fits into my understanding of the philosophy behind this project as trying to draw the data and test distribution for what they are so that the reader can draw his/her own interpretation instead of the author enforcing an interpretation onto the reader.

**Comment by josesho** [comment]
Strictly speaking, the "Control 1 null distribution" is a auto-comparison. So the bootstrap distribution of Control 1 - Control 1. It's not actually the null distribution for any other comparison. In fact, each comparison has its own null distribution, strictly speaking.

You could show P(data|h0) for every comparison here: resample with replacement from Control 1 and Test XX at the same time, compute the mean difference, and highlight the portion of the distribution that exceeds the mean of Test XX. So in fact, you would get a _third_ axes, all of which show the null distributions centered at 0, but with different shapes and different endzones highlighted.

I hope that was clear....?

**Comment by lrq3000** [comment]
Dear @josesho , thank you very much for your detailed reply.

About the bootstrap distribution of Control 1 - Control 1, yes that's what I meant (I've read since then to better understand the stats going on, sorry for the confusion :-) ). My idea would be to allow for a comparison of intervals, with not only the point estimate (bootstrap mean) of Control 1, but a distribution estimate of Control 1, with Control 1 - Control 1 serving as a "normalized" distribution/interval for other comparisons, as to allow interval inference as described in:

Dienes, Z. (2014). [Using Bayes to get the most out of non-significant results](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4114196/). Frontiers in psychology, 5, 781.

Notably [this figure](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4114196/figure/F2/) is quite what I had in mind.

Do you think such comparisons of the confidence intervals between eg, Test 1 - Control 1 vs Control 1 - Control 1 would be sensible and an adequate confidence interval comparison as summarized in this paper? If not, why?

---

About your second paragraph, I thought that p(data|h0) was what we computed here, such as Test 1 - Control 1, by computing a bootstrap mean and standard deviation of both and then do a difference of Test 1 - Control 1 means + scaling of stdev? Are you suggesting that doing this calculation inside each bootstraps (instead of with the final bootstrap estimate from all bootstraps) would provide a more accurate p(data|h0)?

**Comment by lrq3000** [comment]
Ah I think I understand what you mean in the second paragraph, but did you intend to write p(h0|data) perhaps? In which case, I see that we could compute the probability of h0 given data by using the data as a reference and plotting a third axe (or simply using the data as the control group?), but then it would be quite meaningless as we would amalgamate our hypothesis h1 with the data, assuming it's the population instead of a sample, and thus having no meaningful use for inference.

So I think it's safe to drop that idea :-) However, I'm still interested in plotting a distribution for the control condition if that makes sense, as to allow intervals comparison and inference, and making it easier to either be more conservative in inference (by requiring that Test 1 - Control 1 is outside of Control 1 - Control 1 confidence interval for example, instead of just the point estimate at 0) or to make it possible to accept h0 (when Test 1 - Control 1 is contained inside Control 1 - Control 1). Does that make sense? If so, I can work on it :-)

**Comment by lrq3000** [comment]
Please forget what I wrote above about scaling with standard deviation, this is disadvised by several sources, so actually the simple difference is better in the general case :-)
* U is for Unease: Reasons for Mistrusting Overlap Measures for Reporting Clinical Trials, 2010
* https://garstats.wordpress.com/2016/05/02/robust-effect-sizes-for-2-independent-groups/

**Comment by lrq3000** [comment]
Closing this, will reopen more specific PRs
