### ISSUE TITLE
Does not run with more recent versions of dependencies

### ISSUE THREAD

**Issue by kebarr** [ACCLAB/DABEST-python#60]
I have tried to run the test code from the README with the example dataset and get an error (TypeError: must be real number, not list) on the line: 

iris_dabest.mean_diff.plot(), and occurs due to this line in the gapped_lines function:

--> 162     quantiles = data.groupby(x)[y].quantile([0.25, 0.75])\
    163                                   .unstack()\
    164                                   .reindex(index=group_order)

I am using Python3.7 with the following modules:

scipy            1.3.0
seaborn          0.9.0
pandas           0.25.0
numpy            1.17.0
matplotlib       3.1.1

which I notice are more recent versions of the dependencies. I installed dabest using pip. I have also built the cloned version to test and get the same error.

I have forked a copy of the code to see if there is a simple fix.

**Comment by josesho** [comment]
Thanks for this notice; I do need to track if `dabest` plays well with the latest update to numpy and matplotlib. Did you close this because this has been resolved?

**Comment by kebarr** [comment]
I closed it because I found a similar issue during later debugging, and the resolution for that worked here- using pandas 0.24. I have not changed any of the other dependencies so so far it works with later versions of NumPy and matplotlib.

**Comment by josesho** [comment]
Closed with #89
