### ISSUE TITLE
Shared control paired ? 

### ISSUE THREAD

**Issue by chalex-eth** [ACCLAB/DABEST-python#68]
Dear Dabest team,

Thank you for providing a such tool making easy estimation statistic. 

When trying to make a shared control with a paired design with : 
`dabest.load(Data,idx=('Baseline','Post','Off'),paired = True ,id_col = 'ID')`
Data consisting in a 8x3 array.
I got the following error `ValueError: `is_paired` is True, but some idx in ('Baseline', 'Post', 'Off') does not consist only of two groups.`

How to fix this in order to make a shared control with a paired design.

Maybe it can't support a paired design for shared control ? Maybe one day  ?

Thank you

Kind regards, 

Alex

**Comment by josesho** [comment]
Hi,

Do you have a dummy dataset to demonstrate the type of data you have?

Joses

**Comment by AlexChalard** [comment]
Hi, 

Here a bunch of code to reproduce my data shape 

`from scipy.stats import norm # Used in generation of populations.
import pandas as pd
Ns = 8 # The number of samples taken from each population

c1 = norm.rvs(loc=3, scale=0.4, size=Ns)
c2 = norm.rvs(loc=3.5, scale=0.75, size=Ns)
c3 = norm.rvs(loc=3.25, scale=0.4, size=Ns)
id_col = pd.Series(range(1, Ns+1))

df = pd.DataFrame({'Control' : c1,   'Delay1' : c2,  'Delay2' : c3,'ID':id_col})
dab = dabest.load(df,idx=('Control','Delay1','Delay2'),paired = True ,id_col = 'id')`

And the error 

`ValueError: `is_paired` is True, but some idx in ('Control', 'Delay1', 'Delay2') does not consist only of two groups.`

**Comment by josesho** [comment]
I think the plot you want is the successive repeated measures plot, which would include a [parallel coordinates plot](https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.html#parallel-coordinates), and the bootstrap effect sizes below.

![parallel coordinates plot](https://user-images.githubusercontent.com/12838917/64399823-7b159b80-d09c-11e9-9f11-d898a35acd29.png)

A mock up of the plot (which is currently unavailble) would be this:

![repeated-successive-mockup](https://user-images.githubusercontent.com/12838917/64399963-fd9e5b00-d09c-11e9-924f-7f8cdbc131b9.png)

There are plans to include this into the repertoire of estimation graphics; happy to accept your PR if you implement it!

**Comment by ZHANGROU-99** [comment]
Hi,

Thanks for your report! 

We're glad to inform you that we have fixed this issue in the new version 2023.2.14, which has already been released. Please update to the latest version and check out the "Tutorial:Repeated Measures" part of our tutorial(https://acclab.github.io/DABEST-python-docs/repeatedmeasures.html#). 

We're going to close this issue now, but please feel free to reopen it or create a new one if you encounter any further problems.
