### ISSUE TITLE
Plot controls

### ISSUE THREAD

**Issue by araikes** [ACCLAB/DABEST-python#78]
I'm sorry, I'm sure this is easy and I apologize if I've missed a duplicate issue. I'm looking to create and export plots out of DABEST for inclusion with a manuscript. Is there a recommended way of saving high-res plots with axis titles that are readable. 

Thanks

**Comment by araikes** [comment]
Also, is there a way to edit the x-axis tick labels? My variable names aren't pretty and I don't like spaces in them so they don't read nicely.

Thanks

**Comment by josesho** [comment]
> Is there a recommended way of saving high-res plots with axis titles that are readable.

The easiest way to do this is with seaborn's `set` function.

```python
import seaborn as sns
sns.set(style='ticks', font_scale=1)
```
This, however, will scale the font for all text features. To specifically change the axis titles, directly assign the desired font size to matplotlib's `rcParams`.

```python
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 16
```

> Also, is there a way to edit the x-axis tick labels? My variable names aren't pretty and I don't like spaces in them so they don't read nicely.

Consider re-naming your group names in pandas before plotting. To directly 'edit' these, you will need to access the appropriate Axes (see here) and use matplotlib (see [here](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_xticklabels.html) for more details) :

```python
f = two_groups_unpaired.mean_diff.plot();

rawdata_axes = f.axes[0]
effsize_axes = f.axes[1]

rawdata_axes.set_xticklabels(["blue group", "orange!"])
effsize_axes.set_xticklabels(["", "my difference"]) # The xtick is actually plotted at position "1".
```
![image](https://user-images.githubusercontent.com/12838917/66622963-4e651e80-ec1c-11e9-86cc-d39e6ba065f4.png)

Thanks,
Joses

**Comment by araikes** [comment]
Excellent. Thanks @josesho .

**Comment by araikes** [comment]
Sorry, last question on this ( I know it's closed but oh well)... What about removing the legend. I'm using colors for contrast but not to differentiate things to where a legend is needed. Is there anyway to get rid of it. For reference, I'm trying to do the multi-axis plot in the tutorial and the legends end up underneath the other plots.

Thanks

**Comment by araikes** [comment]
Nevermind... took too long but figured it out.

```
topleft_axes = axx.flat[0]
topleft_axes.contrast_axes.get_legend().remove()
```
