### ISSUE TITLE
Bug Plotting: Nan Dropping Drops Rows Prematurely

### ISSUE THREAD

**Issue by adam2392** [ACCLAB/DABEST-python#82]
I am creating a Dataframe with say 10 columns, and 100 rows. When I use Dabest to create an object, and then do subsequent plotting of column 1 vs 2, if there are NANs in other columns (e.g. 8, or 9) in certain rows, then those rows are not used in subsequent analysis: effect size estimation, plotting, etc.

```
_dabest = dabest.load(data=feature_df, 
                          x='nonancol', 
                          y="stat", 
                         idx=(("S", "F"),))
_dabest.cohens_d.plot()
```

does not work, unless I run this first:

`feature_df.drop(['nancol1', 'nancol2'], axis=1, inplace=True)`

Dropping the columns with any nans inside. I presume that the NAN dropping is happening too early and that is why. So even though I don't have NANS in the columns I want, I still don't use those data points.

https://github.com/ACCLAB/DABEST-python/blob/e6cd4b8620bacdfd5954bd6cf005c7cb677414e9/dabest/_classes.py#L149

Looks like some related issues in the past were fixed with that line: 

I would presume an easy fix is to add a drop column in front of that line that removes any columns we are not looking at. (e.g. not passed into the "x" and "y" variables). Lmk if this is the right fix, and I can PR

**Comment by josesho** [comment]
If you can create a dummy dataset as you described and create a unit test for this bug, happy to receive your PR!

**Comment by adam2392** [comment]
Looks like I had to do some pandas updating. I think it was a bug from versioning!
