### ISSUE TITLE
small issues

### ISSUE THREAD

**Issue by smury** [ACCLAB/DABEST-python#84]
Thank you for the great resource!

I just have a little comment regard the website version. The vertical bars indicating the SD are not defined in the auto-generated legend and do not appear at all in the two group plots. 

Also the given email address estimationstats@googlegroups.com does not work.

**Comment by josesho** [comment]
Hi @smury !

Sorry for the inconvenience. You will need to [join the forum](https://groups.google.com/forum/#!forum/estimationstats) before being able to post there. 

Also, it would be useful if you could provide a small dataset via CSV or XLSX to so as to provide a reproducible example of your issue. 

Closing this so we can continue our conversation in the right forum. Thanks!
