### ISSUE TITLE
reflines_kwargs are not honnored when float_contrast=False

### ISSUE THREAD

**Issue by DizietAsahi** [ACCLAB/DABEST-python#87]
When using `float_contrast=False`, the zero reference line does not honor the attributes passed in `reflines_kwargs`.
Compare these two plots for example:

```
two_groups_unpaired.mean_diff.plot(reflines_kwargs=dict(linestyle='dotted'));
two_groups_unpaired.mean_diff.plot(float_contrast=False,reflines_kwargs=dict(linestyle='dotted'))
```

![index](https://user-images.githubusercontent.com/13396853/70797269-7439ab80-1da4-11ea-8b62-530b35e18774.png)
![index1](https://user-images.githubusercontent.com/13396853/70797281-77cd3280-1da4-11ea-81bf-a75f4eec32c9.png)

**Comment by josesho** [comment]
Closed with #89
