### ISSUE TITLE
`slopegraph_kwargs` not working

### ISSUE THREAD

**Issue by DizietAsahi** [ACCLAB/DABEST-python#88]
Trying to change the appearance of the slope lines in a paired graph using `slopegraph_kwargs` result in an Exception:

`two_groups_paired.mean_diff.plot(slopegraph_kwargs=dict(linestyle='dotted'));`

> UnboundLocalError: local variable 'slopegraph_kwargs' referenced before assignment

Also, there is no documentation for the parameter `slopegraph_kwargs` on https://acclab.github.io/DABEST-python-docs/api.html

**Comment by josesho** [comment]
Closed with #89
