### ISSUE TITLE
Problem with plotting mean_diff

### ISSUE THREAD

**Issue by paul-hawkins** [ACCLAB/DABEST-python#98]
The following code should produce two plots, but only the swarm plot is produced, and an error is thrown.

new_df = pd.read_csv('%s/all_ringrmsd_data_only.txt' % rootdir, sep='\t')
s_control = db.load(new_df,idx=('OMEGA','MOE','Macromodel','Desmond','RDKit','Prime'))

s_control.cohens_d

s_control.mean_diff.plot(raw_marker_size=3)

![image](https://user-images.githubusercontent.com/20798654/79793178-5c9fa000-830d-11ea-85a8-18b3ccf340ed.png)

IndexError: index 12 is out of bounds for size 12

[all_ringrmsd_data_only.txt](https://github.com/ACCLAB/DABEST-python/files/4505797/all_ringrmsd_data_only.txt)

**Comment by josesho** [comment]
Hi Paul,

I am able to run your code snippet, on the data you uploaded. 

Can I check: what is your DABEST version when you run

```python
dabest.__version___
```

or

```python
db.__version___
```

given than you import DABEST as db in your example? I'm using the latest version, DABEST v0.3.0.

**Comment by dhuzard** [comment]
Hi @josesho , I have the same issue with my data: an "IndexError: index 10 is out of bounds for size 8" when running the plot function.
I ran the code of @paul-hawkins and I also obtained the same error.
I have DABEST 0.3.0 as well.
I am using Jupyter Notebook.
Note that I can have a graph for only two variables: idx=('OMEGA','MOE'), the problem appears with more than two.
![Dabest two variables](https://user-images.githubusercontent.com/48721374/80107769-cd4bf400-857b-11ea-948d-7c0cf7a67f8a.png)

**Comment by paul-hawkins** [comment]
That’s very odd, as I am using 0.3.0 too.


Paul.

**Comment by josesho** [comment]
@paul-hawkins and @dhuzard ,

This looks suspiciously like issues #67 and #70.

Could I trouble both of you to check what version of pandas you two have installed?

```python
import pandas as pd
pd.__version__
```

Thanks!

**Comment by dhuzard** [comment]
I found out the solution:  upgrading to python 3.8 !

**Comment by paul-hawkins** [comment]
Hi Joses,

'0.25.3'

Does updating to Python 3.8 fix the issue, as dhuzard suggested?


Paul.

**Comment by josesho** [comment]
Hi, @paul-hawkins, I think upgrading pandas to >= 0.26 should do it. Can you give it a go?

**Comment by paul-hawkins** [comment]
Upon upgrading to pandas 1.0.3 I saw this

(oepython36) C:\Users\phawkins>pip install --upgrade pandas
Collecting pandas
  Downloading https://files.pythonhosted.org/packages/d2/81/a1514c993ad8261a2053f356c3ea9a6ad41871a09a8ef9cf46789e371a63/pandas-1.0.3-cp36-cp36m-win_amd64.whl (8.7MB)
     |████████████████████████████████| 8.7MB 819kB/s
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in c:\users\phawkins\anaconda3\envs\oepython36\lib\site-packages (from pandas) (2.8.0)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in c:\users\phawkins\anaconda3\envs\oepython36\lib\site-packages (from pandas) (1.17.2)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\users\phawkins\anaconda3\envs\oepython36\lib\site-packages (from pandas) (2019.2)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\users\phawkins\anaconda3\envs\oepython36\lib\site-packages (from python-dateutil>=2.6.1->pandas) (1.12.0)
ERROR: dabest 0.3.0 has requirement pandas!=0.25.2,~=0.25, but you'll have pandas 1.0.3 which is incompatible.
Installing collected packages: pandas
  Found existing installation: pandas 0.25.1
    Uninstalling pandas-0.25.1:
      Successfully uninstalled pandas-0.25.1
Successfully installed pandas-1.0.3

(oepython36) C:\Users\phawkins>

However, as you said, upgrading works! (albeit with a warning)

C:\Users\phawkins\Anaconda3\envs\oepython36\lib\site-packages\IPython\core\pylabtools.py:128: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect. fig.canvas.print_figure(bytes_io, **kw)

[cid:image001.png@01D61C84.2FCFB2D0]
One last thing – how do I change the font size in the violin plot and the distribution plot? I see I can pass in ‘violinplot_kwargs’ but

violinplot_kwargs={'fontsize':36})

does not work. I can’t see how to go about changing the distribution plot at all.

Thanks for all the help Joses,


Paul.

**Comment by JAnns98** [comment]
Apologies for this never being followed up with here. I hope all was sorted. I will close this issue for now, however, it can be reopened in the future if needed.
